#---
# tasks file for nginx_php_mysql
#- import_playbook: user.yml
#- import_playbook: packages.yml
#- import_playbook: nginx.yml
#- import_playbook: php.yml

---
- name: Apply common configuration on webserver virtual machine
  hosts: IPVirtualMachine
  gather_facts: no
  ignore_errors: yes

  roles:
    - { role: packages }
    - { role: nginx }
    - { role: php }
    - { role: vsftpd }


