---
#- name: Install basic packages before install nginx.
    - name: Install a list of packages
      yum:
         name:
           - epel-release
           - vim
           - wget
           - curl
         state: present
    - name: upgrade all packages
      yum:
         name: '*'
         state: latest
