---
- name: Task nginx installation
  hosts: 192.168.51.26
  tasks:
    - name: Install Nginx latest version
      yum: 
         name: nginx 
         state: latest
    - name: Nginx - Enabling on boot
      service:
         name: nginx
         enabled: yes

