---
- name: Install basic packages before install nginx.
  hosts: 192.168.33.107
  tasks:
    - name: 
      yum: name={{ item }} update_cache=yes state=present
      with_items:
        - epel-release
        - vim
        - git
        - wget
        - curl
  tags: packages
