---
- name: Install basic packages before install nginx.
  hosts: 192.168.51.26
  tasks:
    - name: Install a list of packages
      yum:
         name:
           - epel-release
           - vim
           - wget
           - curl
         state: present
    - name: upgrade all packages
      yum:
         name: '*'
         state: latest
