---
- name: Task PHP and modules installation
  hosts: 192.168.51.26
  tasks:
    - name: Install Remi Release repository
      yum: 
         name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
         state: present
    - name: Install MysQL Community repository
      yum:
         name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
         state: present
    - name: Install a list of PHP modules
      yum:
         name:
             - php-mysqli
             - php-xml
             - php-gd
             - php-soap
             - php-mcrypt
             - php-xmlrpc
             - php-pdo
             - php-pdo_sqlite
             - php-posix
             - php-mbstring
         state: present
         enablerepo: remi-php72
         
