---
- name: Install MysQL Community repository
  yum:
    name: http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm
    state: present
- name: Install MySQL Community Server 5.6.49
  yum:
    name: mysql-community-server
    state: present
- name: Start Service MySQL
  systemd:
    name: mysqld
    state: restarted
    enabled: yes
- name: Install MySQL-python library
  yum:
    name:
      - MySQL-python

- name: Set MySQL root password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{ mysqlroot_passwd }}'
    state: present
