---
- name: Install MysQL Community repository
  yum:
    name: http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm
    state: present
- name: Install MySQL Community Server 5.6.49
  yum:
    name: mysql-community-server
    state: present

- name: Start Service MySQL
  systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Get root password
  shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}'"
  register: root_password

